name: manage-azure-policy-563727ad
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Alert_Monitor_Policy_Assignment_Rules_29eee609-6fcb-4ec4-80a5-9debd82d31e1/**'
#      - 'initiatives/Activity_Log_Alerts_-_Policy_Assignment_7aa414e51063417d80429255/**'
#      - .github/workflows/manage-azure-policy-563727ad.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_563727ad}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Alert_Monitor_Policy_Assignment_Rules_29eee609-6fcb-4ec4-80a5-9debd82d31e1/**
          initiatives/Activity_Log_Alerts_-_Policy_Assignment_7aa414e51063417d80429255/**
